/*
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.motiarc.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.palladiosimulator.xtext.motiarc.parser.antlr.internal.InternalMontiArcDSLParser;
import org.palladiosimulator.xtext.motiarc.services.MontiArcDSLGrammarAccess;

public class MontiArcDSLParser extends AbstractAntlrParser {

	@Inject
	private MontiArcDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMontiArcDSLParser createParser(XtextTokenStream stream) {
		return new InternalMontiArcDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MACompilationUnit";
	}

	public MontiArcDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MontiArcDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
