/**
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.motiarc.mcBasics;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getImportUri <em>Import Uri</em>}</li>
 *   <li>{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#isStar <em>Star</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.xtext.motiarc.mcBasics.McBasicsPackage#getImportStatements()
 * @model
 * @generated
 */
public interface ImportStatements extends EObject
{
  /**
   * Returns the value of the '<em><b>Import Uri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Uri</em>' attribute.
   * @see #setImportUri(String)
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.McBasicsPackage#getImportStatements_ImportUri()
   * @model
   * @generated
   */
  String getImportUri();

  /**
   * Sets the value of the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getImportUri <em>Import Uri</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import Uri</em>' attribute.
   * @see #getImportUri()
   * @generated
   */
  void setImportUri(String value);

  /**
   * Returns the value of the '<em><b>Star</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Star</em>' attribute.
   * @see #setStar(boolean)
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.McBasicsPackage#getImportStatements_Star()
   * @model
   * @generated
   */
  boolean isStar();

  /**
   * Sets the value of the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#isStar <em>Star</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Star</em>' attribute.
   * @see #isStar()
   * @generated
   */
  void setStar(boolean value);

} // ImportStatements
