/**
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.motiarc.mcBasics;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.palladiosimulator.xtext.motiarc.mcBasics.McBasicsFactory
 * @model kind="package"
 * @generated
 */
public interface McBasicsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mcBasics";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.palladiosimulator.org/xtext/moticore/MCBasics";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mcBasics";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  McBasicsPackage eINSTANCE = org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ImportStatementsImpl <em>Import Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ImportStatementsImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getImportStatements()
   * @generated
   */
  int IMPORT_STATEMENTS = 0;

  /**
   * The feature id for the '<em><b>Import Uri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_STATEMENTS__IMPORT_URI = 0;

  /**
   * The feature id for the '<em><b>Star</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_STATEMENTS__STAR = 1;

  /**
   * The number of structural features of the '<em>Import Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_STATEMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.PackageImpl <em>Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.PackageImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getPackage()
   * @generated
   */
  int PACKAGE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__NAME = 0;

  /**
   * The number of structural features of the '<em>Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.TypeImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getType()
   * @generated
   */
  int TYPE = 2;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCPrimitiveTypeImpl <em>MC Primitive Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCPrimitiveTypeImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getMCPrimitiveType()
   * @generated
   */
  int MC_PRIMITIVE_TYPE = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_PRIMITIVE_TYPE__TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MC Primitive Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_PRIMITIVE_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCArrayTypeImpl <em>MC Array Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCArrayTypeImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getMCArrayType()
   * @generated
   */
  int MC_ARRAY_TYPE = 4;

  /**
   * The number of structural features of the '<em>MC Array Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_ARRAY_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ExpressionImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 5;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.LiteralExpressionImpl <em>Literal Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.LiteralExpressionImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getLiteralExpression()
   * @generated
   */
  int LITERAL_EXPRESSION = 6;

  /**
   * The number of structural features of the '<em>Literal Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.NumberLiteralImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 7;

  /**
   * The feature id for the '<em><b>Literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__LITERAL = LITERAL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = LITERAL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.StringLiteralImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 8;

  /**
   * The feature id for the '<em><b>Literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__LITERAL = LITERAL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = LITERAL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.NameExpressionImpl <em>Name Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.NameExpressionImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getNameExpression()
   * @generated
   */
  int NAME_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_EXPRESSION__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Name Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentsImpl <em>Arguments</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentsImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getArguments()
   * @generated
   */
  int ARGUMENTS = 10;

  /**
   * The feature id for the '<em><b>Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTS__ARGUMENTS = 0;

  /**
   * The number of structural features of the '<em>Arguments</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentImpl <em>Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getArgument()
   * @generated
   */
  int ARGUMENT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT__EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements <em>Import Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Statements</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements
   * @generated
   */
  EClass getImportStatements();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getImportUri <em>Import Uri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import Uri</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getImportUri()
   * @see #getImportStatements()
   * @generated
   */
  EAttribute getImportStatements_ImportUri();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getStar <em>Star</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Star</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getStar()
   * @see #getImportStatements()
   * @generated
   */
  EAttribute getImportStatements_Star();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Package <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Package
   * @generated
   */
  EClass getPackage();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Package#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Package#getName()
   * @see #getPackage()
   * @generated
   */
  EAttribute getPackage_Name();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.MCPrimitiveType <em>MC Primitive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Primitive Type</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.MCPrimitiveType
   * @generated
   */
  EClass getMCPrimitiveType();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.MCPrimitiveType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.MCPrimitiveType#getType()
   * @see #getMCPrimitiveType()
   * @generated
   */
  EAttribute getMCPrimitiveType_Type();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.MCArrayType <em>MC Array Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Array Type</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.MCArrayType
   * @generated
   */
  EClass getMCArrayType();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.LiteralExpression <em>Literal Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal Expression</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.LiteralExpression
   * @generated
   */
  EClass getLiteralExpression();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.NumberLiteral#getLiteral <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Literal</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.NumberLiteral#getLiteral()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Literal();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.StringLiteral#getLiteral <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Literal</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.StringLiteral#getLiteral()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Literal();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.NameExpression <em>Name Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Name Expression</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.NameExpression
   * @generated
   */
  EClass getNameExpression();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.NameExpression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.NameExpression#getName()
   * @see #getNameExpression()
   * @generated
   */
  EAttribute getNameExpression_Name();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Arguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arguments</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Arguments
   * @generated
   */
  EClass getArguments();

  /**
   * Returns the meta object for the containment reference list '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Arguments#getArguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arguments</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Arguments#getArguments()
   * @see #getArguments()
   * @generated
   */
  EReference getArguments_Arguments();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Argument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Argument</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Argument
   * @generated
   */
  EClass getArgument();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Argument#isName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Argument#isName()
   * @see #getArgument()
   * @generated
   */
  EAttribute getArgument_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Argument#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Argument#getExpression()
   * @see #getArgument()
   * @generated
   */
  EReference getArgument_Expression();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  McBasicsFactory getMcBasicsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ImportStatementsImpl <em>Import Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ImportStatementsImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getImportStatements()
     * @generated
     */
    EClass IMPORT_STATEMENTS = eINSTANCE.getImportStatements();

    /**
     * The meta object literal for the '<em><b>Import Uri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT_STATEMENTS__IMPORT_URI = eINSTANCE.getImportStatements_ImportUri();

    /**
     * The meta object literal for the '<em><b>Star</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT_STATEMENTS__STAR = eINSTANCE.getImportStatements_Star();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.PackageImpl <em>Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.PackageImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getPackage()
     * @generated
     */
    EClass PACKAGE = eINSTANCE.getPackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE__NAME = eINSTANCE.getPackage_Name();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.TypeImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCPrimitiveTypeImpl <em>MC Primitive Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCPrimitiveTypeImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getMCPrimitiveType()
     * @generated
     */
    EClass MC_PRIMITIVE_TYPE = eINSTANCE.getMCPrimitiveType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MC_PRIMITIVE_TYPE__TYPE = eINSTANCE.getMCPrimitiveType_Type();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCArrayTypeImpl <em>MC Array Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCArrayTypeImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getMCArrayType()
     * @generated
     */
    EClass MC_ARRAY_TYPE = eINSTANCE.getMCArrayType();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ExpressionImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.LiteralExpressionImpl <em>Literal Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.LiteralExpressionImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getLiteralExpression()
     * @generated
     */
    EClass LITERAL_EXPRESSION = eINSTANCE.getLiteralExpression();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.NumberLiteralImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Literal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__LITERAL = eINSTANCE.getNumberLiteral_Literal();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.StringLiteralImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Literal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__LITERAL = eINSTANCE.getStringLiteral_Literal();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.NameExpressionImpl <em>Name Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.NameExpressionImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getNameExpression()
     * @generated
     */
    EClass NAME_EXPRESSION = eINSTANCE.getNameExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAME_EXPRESSION__NAME = eINSTANCE.getNameExpression_Name();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentsImpl <em>Arguments</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentsImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getArguments()
     * @generated
     */
    EClass ARGUMENTS = eINSTANCE.getArguments();

    /**
     * The meta object literal for the '<em><b>Arguments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARGUMENTS__ARGUMENTS = eINSTANCE.getArguments_Arguments();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentImpl <em>Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getArgument()
     * @generated
     */
    EClass ARGUMENT = eINSTANCE.getArgument();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARGUMENT__NAME = eINSTANCE.getArgument_Name();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARGUMENT__EXPRESSION = eINSTANCE.getArgument_Expression();

  }

} //McBasicsPackage
