/**
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.motiarc.mcBasics;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.palladiosimulator.xtext.motiarc.mcBasics.McBasicsFactory
 * @model kind="package"
 * @generated
 */
public interface McBasicsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mcBasics";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.palladiosimulator.org/xtext/moticore/MCBasics";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mcBasics";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  McBasicsPackage eINSTANCE = org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ImportStatementsImpl <em>Import Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ImportStatementsImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getImportStatements()
   * @generated
   */
  int IMPORT_STATEMENTS = 0;

  /**
   * The feature id for the '<em><b>Import Uri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_STATEMENTS__IMPORT_URI = 0;

  /**
   * The feature id for the '<em><b>Star</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_STATEMENTS__STAR = 1;

  /**
   * The number of structural features of the '<em>Import Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_STATEMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.PackageImpl <em>Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.PackageImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getPackage()
   * @generated
   */
  int PACKAGE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__NAME = 0;

  /**
   * The number of structural features of the '<em>Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.TypeImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getType()
   * @generated
   */
  int TYPE = 2;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCPrimitiveTypeImpl <em>MC Primitive Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCPrimitiveTypeImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getMCPrimitiveType()
   * @generated
   */
  int MC_PRIMITIVE_TYPE = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_PRIMITIVE_TYPE__TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MC Primitive Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_PRIMITIVE_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCArrayTypeImpl <em>MC Array Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCArrayTypeImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getMCArrayType()
   * @generated
   */
  int MC_ARRAY_TYPE = 4;

  /**
   * The number of structural features of the '<em>MC Array Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MC_ARRAY_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ExpressionImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentsImpl <em>Arguments</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentsImpl
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getArguments()
   * @generated
   */
  int ARGUMENTS = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTS__NAME = 0;

  /**
   * The number of structural features of the '<em>Arguments</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTS_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements <em>Import Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Statements</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements
   * @generated
   */
  EClass getImportStatements();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getImportUri <em>Import Uri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import Uri</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getImportUri()
   * @see #getImportStatements()
   * @generated
   */
  EAttribute getImportStatements_ImportUri();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getStar <em>Star</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Star</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.ImportStatements#getStar()
   * @see #getImportStatements()
   * @generated
   */
  EAttribute getImportStatements_Star();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Package <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Package
   * @generated
   */
  EClass getPackage();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Package#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Package#getName()
   * @see #getPackage()
   * @generated
   */
  EAttribute getPackage_Name();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.MCPrimitiveType <em>MC Primitive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Primitive Type</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.MCPrimitiveType
   * @generated
   */
  EClass getMCPrimitiveType();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.MCPrimitiveType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.MCPrimitiveType#getType()
   * @see #getMCPrimitiveType()
   * @generated
   */
  EAttribute getMCPrimitiveType_Type();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.MCArrayType <em>MC Array Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MC Array Type</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.MCArrayType
   * @generated
   */
  EClass getMCArrayType();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Expression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Expression#getName()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Name();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Arguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arguments</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Arguments
   * @generated
   */
  EClass getArguments();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.xtext.motiarc.mcBasics.Arguments#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.palladiosimulator.xtext.motiarc.mcBasics.Arguments#getName()
   * @see #getArguments()
   * @generated
   */
  EAttribute getArguments_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  McBasicsFactory getMcBasicsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ImportStatementsImpl <em>Import Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ImportStatementsImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getImportStatements()
     * @generated
     */
    EClass IMPORT_STATEMENTS = eINSTANCE.getImportStatements();

    /**
     * The meta object literal for the '<em><b>Import Uri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT_STATEMENTS__IMPORT_URI = eINSTANCE.getImportStatements_ImportUri();

    /**
     * The meta object literal for the '<em><b>Star</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT_STATEMENTS__STAR = eINSTANCE.getImportStatements_Star();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.PackageImpl <em>Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.PackageImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getPackage()
     * @generated
     */
    EClass PACKAGE = eINSTANCE.getPackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE__NAME = eINSTANCE.getPackage_Name();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.TypeImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCPrimitiveTypeImpl <em>MC Primitive Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCPrimitiveTypeImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getMCPrimitiveType()
     * @generated
     */
    EClass MC_PRIMITIVE_TYPE = eINSTANCE.getMCPrimitiveType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MC_PRIMITIVE_TYPE__TYPE = eINSTANCE.getMCPrimitiveType_Type();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCArrayTypeImpl <em>MC Array Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.MCArrayTypeImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getMCArrayType()
     * @generated
     */
    EClass MC_ARRAY_TYPE = eINSTANCE.getMCArrayType();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ExpressionImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NAME = eINSTANCE.getExpression_Name();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentsImpl <em>Arguments</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.ArgumentsImpl
     * @see org.palladiosimulator.xtext.motiarc.mcBasics.impl.McBasicsPackageImpl#getArguments()
     * @generated
     */
    EClass ARGUMENTS = eINSTANCE.getArguments();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARGUMENTS__NAME = eINSTANCE.getArguments_Name();

  }

} //McBasicsPackage
