/**
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.motiarc.montiCoreCD;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CD Enum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.xtext.motiarc.montiCoreCD.CDEnum#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.xtext.motiarc.montiCoreCD.MontiCoreCDPackage#getCDEnum()
 * @model
 * @generated
 */
public interface CDEnum extends CDDefinition
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see org.palladiosimulator.xtext.motiarc.montiCoreCD.MontiCoreCDPackage#getCDEnum_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // CDEnum
