/**
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.motiarc.montiCoreCD;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.palladiosimulator.xtext.motiarc.montiCoreCD.MontiCoreCDPackage
 * @generated
 */
public interface MontiCoreCDFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MontiCoreCDFactory eINSTANCE = org.palladiosimulator.xtext.motiarc.montiCoreCD.impl.MontiCoreCDFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Class Diagram Compilation Unit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Diagram Compilation Unit</em>'.
   * @generated
   */
  ClassDiagramCompilationUnit createClassDiagramCompilationUnit();

  /**
   * Returns a new object of class '<em>Class Diagram</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Diagram</em>'.
   * @generated
   */
  ClassDiagram createClassDiagram();

  /**
   * Returns a new object of class '<em>CD Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CD Definition</em>'.
   * @generated
   */
  CDDefinition createCDDefinition();

  /**
   * Returns a new object of class '<em>CD Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CD Class</em>'.
   * @generated
   */
  CDClass createCDClass();

  /**
   * Returns a new object of class '<em>CD Enum</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CD Enum</em>'.
   * @generated
   */
  CDEnum createCDEnum();

  /**
   * Returns a new object of class '<em>Member</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Member</em>'.
   * @generated
   */
  Member createMember();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MontiCoreCDPackage getMontiCoreCDPackage();

} //MontiCoreCDFactory
