/*
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.motiarc;

import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.eclipse.xtext.resource.generic.GenericResourceServiceProvider;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MontiArcDSLStandaloneSetup extends MontiArcDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new MontiArcDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
}
